//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  packages: Packages;
  packagesConnection: PackagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPackagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPackagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PackagesFilter>;
};

export type DocumentFilter = {
  packages?: InputMaybe<PackagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Packages | Folder;

export type PackagesItemsDetails = {
  __typename?: 'PackagesItemsDetails';
  icon?: Maybe<Scalars['String']['output']>;
  es?: Maybe<Scalars['String']['output']>;
  en?: Maybe<Scalars['String']['output']>;
};

export type PackagesItems = {
  __typename?: 'PackagesItems';
  image?: Maybe<Scalars['String']['output']>;
  nameEs?: Maybe<Scalars['String']['output']>;
  nameEn?: Maybe<Scalars['String']['output']>;
  nightsEs?: Maybe<Scalars['String']['output']>;
  nightsEn?: Maybe<Scalars['String']['output']>;
  descEs?: Maybe<Scalars['String']['output']>;
  descEn?: Maybe<Scalars['String']['output']>;
  priceEs?: Maybe<Scalars['String']['output']>;
  priceEn?: Maybe<Scalars['String']['output']>;
  panel?: Maybe<Scalars['String']['output']>;
  objPos?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Array<Maybe<PackagesItemsDetails>>>;
};

export type Packages = Node & Document & {
  __typename?: 'Packages';
  headerKickerEs?: Maybe<Scalars['String']['output']>;
  headerKickerEn?: Maybe<Scalars['String']['output']>;
  headerTitleEs?: Maybe<Scalars['String']['output']>;
  headerTitleEn?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PackagesItems>>>;
  noteEs?: Maybe<Scalars['String']['output']>;
  noteEn?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PackagesItemsDetailsFilter = {
  icon?: InputMaybe<StringFilter>;
  es?: InputMaybe<StringFilter>;
  en?: InputMaybe<StringFilter>;
};

export type PackagesItemsFilter = {
  image?: InputMaybe<ImageFilter>;
  nameEs?: InputMaybe<StringFilter>;
  nameEn?: InputMaybe<StringFilter>;
  nightsEs?: InputMaybe<StringFilter>;
  nightsEn?: InputMaybe<StringFilter>;
  descEs?: InputMaybe<StringFilter>;
  descEn?: InputMaybe<StringFilter>;
  priceEs?: InputMaybe<StringFilter>;
  priceEn?: InputMaybe<StringFilter>;
  panel?: InputMaybe<StringFilter>;
  objPos?: InputMaybe<StringFilter>;
  details?: InputMaybe<PackagesItemsDetailsFilter>;
};

export type PackagesFilter = {
  headerKickerEs?: InputMaybe<StringFilter>;
  headerKickerEn?: InputMaybe<StringFilter>;
  headerTitleEs?: InputMaybe<StringFilter>;
  headerTitleEn?: InputMaybe<StringFilter>;
  items?: InputMaybe<PackagesItemsFilter>;
  noteEs?: InputMaybe<StringFilter>;
  noteEn?: InputMaybe<StringFilter>;
};

export type PackagesConnectionEdges = {
  __typename?: 'PackagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Packages>;
};

export type PackagesConnection = Connection & {
  __typename?: 'PackagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PackagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePackages: Packages;
  createPackages: Packages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePackagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PackagesMutation;
};


export type MutationCreatePackagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PackagesMutation;
};

export type DocumentUpdateMutation = {
  packages?: InputMaybe<PackagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  packages?: InputMaybe<PackagesMutation>;
};

export type PackagesItemsDetailsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  es?: InputMaybe<Scalars['String']['input']>;
  en?: InputMaybe<Scalars['String']['input']>;
};

export type PackagesItemsMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  nameEs?: InputMaybe<Scalars['String']['input']>;
  nameEn?: InputMaybe<Scalars['String']['input']>;
  nightsEs?: InputMaybe<Scalars['String']['input']>;
  nightsEn?: InputMaybe<Scalars['String']['input']>;
  descEs?: InputMaybe<Scalars['String']['input']>;
  descEn?: InputMaybe<Scalars['String']['input']>;
  priceEs?: InputMaybe<Scalars['String']['input']>;
  priceEn?: InputMaybe<Scalars['String']['input']>;
  panel?: InputMaybe<Scalars['String']['input']>;
  objPos?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Array<InputMaybe<PackagesItemsDetailsMutation>>>;
};

export type PackagesMutation = {
  headerKickerEs?: InputMaybe<Scalars['String']['input']>;
  headerKickerEn?: InputMaybe<Scalars['String']['input']>;
  headerTitleEs?: InputMaybe<Scalars['String']['input']>;
  headerTitleEn?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PackagesItemsMutation>>>;
  noteEs?: InputMaybe<Scalars['String']['input']>;
  noteEn?: InputMaybe<Scalars['String']['input']>;
};

export type PackagesPartsFragment = { __typename: 'Packages', headerKickerEs?: string | null, headerKickerEn?: string | null, headerTitleEs?: string | null, headerTitleEn?: string | null, noteEs?: string | null, noteEn?: string | null, items?: Array<{ __typename: 'PackagesItems', image?: string | null, nameEs?: string | null, nameEn?: string | null, nightsEs?: string | null, nightsEn?: string | null, descEs?: string | null, descEn?: string | null, priceEs?: string | null, priceEn?: string | null, panel?: string | null, objPos?: string | null, details?: Array<{ __typename: 'PackagesItemsDetails', icon?: string | null, es?: string | null, en?: string | null } | null> | null } | null> | null };

export type PackagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PackagesQuery = { __typename?: 'Query', packages: { __typename: 'Packages', id: string, headerKickerEs?: string | null, headerKickerEn?: string | null, headerTitleEs?: string | null, headerTitleEn?: string | null, noteEs?: string | null, noteEn?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PackagesItems', image?: string | null, nameEs?: string | null, nameEn?: string | null, nightsEs?: string | null, nightsEn?: string | null, descEs?: string | null, descEn?: string | null, priceEs?: string | null, priceEn?: string | null, panel?: string | null, objPos?: string | null, details?: Array<{ __typename: 'PackagesItemsDetails', icon?: string | null, es?: string | null, en?: string | null } | null> | null } | null> | null } };

export type PackagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PackagesFilter>;
}>;


export type PackagesConnectionQuery = { __typename?: 'Query', packagesConnection: { __typename?: 'PackagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PackagesConnectionEdges', cursor: string, node?: { __typename: 'Packages', id: string, headerKickerEs?: string | null, headerKickerEn?: string | null, headerTitleEs?: string | null, headerTitleEn?: string | null, noteEs?: string | null, noteEn?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PackagesItems', image?: string | null, nameEs?: string | null, nameEn?: string | null, nightsEs?: string | null, nightsEn?: string | null, descEs?: string | null, descEn?: string | null, priceEs?: string | null, priceEn?: string | null, panel?: string | null, objPos?: string | null, details?: Array<{ __typename: 'PackagesItemsDetails', icon?: string | null, es?: string | null, en?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export const PackagesPartsFragmentDoc = gql`
    fragment PackagesParts on Packages {
  __typename
  headerKickerEs
  headerKickerEn
  headerTitleEs
  headerTitleEn
  items {
    __typename
    image
    nameEs
    nameEn
    nightsEs
    nightsEn
    descEs
    descEn
    priceEs
    priceEn
    panel
    objPos
    details {
      __typename
      icon
      es
      en
    }
  }
  noteEs
  noteEn
}
    `;
export const PackagesDocument = gql`
    query packages($relativePath: String!) {
  packages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PackagesParts
  }
}
    ${PackagesPartsFragmentDoc}`;
export const PackagesConnectionDocument = gql`
    query packagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PackagesFilter) {
  packagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PackagesParts
      }
    }
  }
}
    ${PackagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      packages(variables: PackagesQueryVariables, options?: C): Promise<{data: PackagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesQueryVariables, query: string}> {
        return requester<{data: PackagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesQueryVariables, query: string}, PackagesQueryVariables>(PackagesDocument, variables, options);
      },
    packagesConnection(variables?: PackagesConnectionQueryVariables, options?: C): Promise<{data: PackagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesConnectionQueryVariables, query: string}> {
        return requester<{data: PackagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesConnectionQueryVariables, query: string}, PackagesConnectionQueryVariables>(PackagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  